server:
  port: 8080

spring:
  application:
    name: backend

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  config:
    import: "configserver:"  # Config Server'dan tüm ayarları al

# Config Server'dan clickhouse.datasource ayarlarını alacak.

csv:
  watch:
    directory: ./csv-files
