# Spring Boot uygulamasının ana yapılandırma dosyası
server:
  port: 8080 # Sunucu portu
spring:
  application:
    name: backend # Uygulamanın adı
  cloud:
    config:
      uri: http://localhost:8888 # Konfigürasyon sunucusunun adresi
  config:
    import: "configserver:" # Harici konfigürasyon sunucusundan ayarları içe aktarır

# CSV işleme konfigürasyonu
csv:
  watch:
    directory: ./csv-files # CSV dosyalarının izleneceği dizin
